#!/usr/bin/env bash
# agent-setup.sh — Interactive setup wizard for CCC agent nodes.
# Run on any non-hub machine to join the fleet.
# Generates ~/.acc/.env, mounts AccFS, and registers with the hub.

set -euo pipefail

ACC_DIR="${HOME}/.acc"
ENV_FILE="${ACC_DIR}/.env"
WORKSPACE="${ACC_DIR}/workspace"

# ── Helpers ────────────────────────────────────────────────────────────────────
bold()  { printf '\033[1m%s\033[0m\n' "$*"; }
ask()   { local prompt="$1" default="${2:-}" var; read -rp "$(bold "$prompt") [${default}]: " var; echo "${var:-$default}"; }
askq()  { local prompt="$1" var; read -rsp "$(bold "$prompt"): " var; echo; echo "$var"; }
info()  { printf '  → %s\n' "$*"; }
ok()    { printf '  ✓ %s\n' "$*"; }
warn()  { printf '  ⚠ %s\n' "$*" >&2; }

echo
bold "═══════════════════════════════════════════════════════"
bold " CCC Agent Setup Wizard"
bold "═══════════════════════════════════════════════════════"
echo
echo "This wizard joins this machine to an existing CCC fleet."
echo "You will need the hub URL and an admin token to register."
echo

# ── Collect values ─────────────────────────────────────────────────────────────
AGENT_NAME=$(ask "Agent name (unique in fleet)" "$(hostname -s)")
AGENT_HOST=$(ask "Hostname (as seen by other agents)" "$(hostname -s)")

ACC_URL=$(ask "Hub CCC URL (ACC_URL)" "")
while [[ -z "$ACC_URL" ]]; do
  warn "ACC_URL is required (e.g. http://192.168.1.10:8789)"
  ACC_URL=$(ask "Hub CCC URL" "")
done

CCC_ADMIN_TOKEN=$(askq "Hub admin token (to register this agent)")

echo
info "Registering agent '${AGENT_NAME}' with ${ACC_URL}..."

# Register and get agent token
REGISTER_RESPONSE=$(curl -sf -X POST "${ACC_URL}/api/agents/register" \
  -H "Authorization: Bearer ${CCC_ADMIN_TOKEN}" \
  -H "Content-Type: application/json" \
  -d "{\"name\":\"${AGENT_NAME}\",\"host\":\"${AGENT_HOST}\",\"type\":\"full\"}" 2>/dev/null || echo "")

if [[ -z "$REGISTER_RESPONSE" ]]; then
  warn "Registration failed — check ACC_URL and admin token"
  exit 1
fi

ACC_AGENT_TOKEN=$(echo "$REGISTER_RESPONSE" | python3 -c "import json,sys; print(json.load(sys.stdin).get('token',''))" 2>/dev/null || echo "")
if [[ -z "$ACC_AGENT_TOKEN" ]]; then
  warn "No token in response: $REGISTER_RESPONSE"
  exit 1
fi
ok "Registered — token: ${ACC_AGENT_TOKEN:0:20}..."

# Fetch SMB credentials from hub
info "Fetching SMB credentials from hub secrets..."
SMB_HOST=$(curl -sf -H "Authorization: Bearer ${ACC_AGENT_TOKEN}" "${ACC_URL}/api/secrets/rocky_smb_host" 2>/dev/null \
  | python3 -c "import json,sys; print(json.load(sys.stdin).get('value',''))" 2>/dev/null || echo "")
SMB_SHARE=$(curl -sf -H "Authorization: Bearer ${ACC_AGENT_TOKEN}" "${ACC_URL}/api/secrets/rocky_smb_share" 2>/dev/null \
  | python3 -c "import json,sys; print(json.load(sys.stdin).get('value','accfs'))" 2>/dev/null || echo "accfs")
SMB_USER=$(curl -sf -H "Authorization: Bearer ${ACC_AGENT_TOKEN}" "${ACC_URL}/api/secrets/rocky_smb_user" 2>/dev/null \
  | python3 -c "import json,sys; print(json.load(sys.stdin).get('value',''))" 2>/dev/null || echo "")
SMB_PASS=$(curl -sf -H "Authorization: Bearer ${ACC_AGENT_TOKEN}" "${ACC_URL}/api/secrets/SMB_PASSWORD" 2>/dev/null \
  | python3 -c "import json,sys; print(json.load(sys.stdin).get('value',''))" 2>/dev/null || echo "")

[[ -z "$SMB_HOST" ]] && { warn "Could not fetch SMB_HOST from hub — AccFS mount will need manual setup"; SMB_HOST=$(ask "SMB host IP" ""); }
[[ -z "$SMB_USER" ]] && SMB_USER=$(ask "SMB username" "$(whoami)")

ANTHROPIC_KEY=$(askq "Anthropic API key (optional, press Enter to skip)")
NVIDIA_KEY=$(askq "NVIDIA inference API key (optional, press Enter to skip)")
HAS_GPU=$(ask "Does this agent have a GPU? (y/n)" "n")

echo
bold "══ Summary ══════════════════════════════════════════════"
info "Agent name: ${AGENT_NAME}"
info "Hub:        ${ACC_URL}"
info "SMB host:   ${SMB_HOST:-not set}"
info "Token:      ${ACC_AGENT_TOKEN:0:20}..."
echo

# ── Create ~/.acc structure ────────────────────────────────────────────────────
mkdir -p "${ACC_DIR}/logs" "${ACC_DIR}/shared" "${ACC_DIR}/bin"

# ── Write .env ─────────────────────────────────────────────────────────────────
cat > "${ENV_FILE}" << EOF
# CCC Agent Configuration — generated by deploy/wizard/agent-setup.sh
# Do not commit this file.

# Identity
AGENT_NAME=${AGENT_NAME}
AGENT_HOST=${AGENT_HOST}

# Network
ACC_URL=${ACC_URL}
TOKENHUB_URL=http://localhost:8090
ANTHROPIC_BASE_URL=http://localhost:9099

# Auth
ACC_AGENT_TOKEN=${ACC_AGENT_TOKEN}

# Storage
ACC_SHARED_DIR=${ACC_DIR}/shared
SMB_HOST=${SMB_HOST}
SMB_SHARE=${SMB_SHARE}
SMB_USER=${SMB_USER}

# Inference
$([ -n "$ANTHROPIC_KEY" ] && echo "ANTHROPIC_API_KEY=${ANTHROPIC_KEY}" || echo "# ANTHROPIC_API_KEY=")
$([ -n "$NVIDIA_KEY" ] && echo "NVIDIA_API_KEY=${NVIDIA_KEY}" || echo "# NVIDIA_API_KEY=")
$([ "$HAS_GPU" = "y" ] && echo "AGENT_HAS_GPU=true" || echo "AGENT_HAS_GPU=false")
EOF
chmod 600 "${ENV_FILE}"
ok ".env written to ${ENV_FILE}"

# ── Clone workspace ────────────────────────────────────────────────────────────
REPO_URL=$(ask "Git repo URL to clone as workspace" "")
if [[ -n "$REPO_URL" ]]; then
  if [[ ! -d "${WORKSPACE}/.git" ]]; then
    git clone "$REPO_URL" "$WORKSPACE" && ok "Workspace cloned to ${WORKSPACE}"
  else
    git -C "$WORKSPACE" pull --rebase && ok "Workspace updated"
  fi
fi

# ── Run AccFS migration ────────────────────────────────────────────────────────
if [[ -n "$SMB_PASS" ]] && [[ -n "$SMB_HOST" ]] && [[ -f "${WORKSPACE}/deploy/migrate.sh" ]]; then
  info "Running AccFS mount setup..."
  export SMB_HOST SMB_SHARE SMB_USER SMB_PASS ACC_URL ACC_AGENT_TOKEN
  bash "${WORKSPACE}/deploy/migrate.sh" 0019 2>/dev/null && ok "AccFS mount configured"
else
  warn "Skipping AccFS mount — run manually: bash deploy/migrate.sh 0019"
fi

# ── Generate SOUL.md scaffold ──────────────────────────────────────────────────
SOUL_FILE="${WORKSPACE}/deploy/agents/${AGENT_NAME}/SOUL.md"
if [[ -n "$WORKSPACE" ]] && [[ ! -f "$SOUL_FILE" ]]; then
  mkdir -p "$(dirname "$SOUL_FILE")"
  ARCH=$(uname -m)
  OS_NAME=$(uname -s)
  cat > "$SOUL_FILE" << SOUL
# ${AGENT_NAME} — Soul

## Who I Am

{Describe this agent's role and personality.}

## Hardware Capabilities

- **Architecture:** ${ARCH}
- **OS:** ${OS_NAME}
- **GPU:** $([ "$HAS_GPU" = "y" ] && echo "{describe GPU}" || echo "none")
- **Service manager:** $(command -v systemctl &>/dev/null && echo "systemd" || command -v launchctl &>/dev/null && echo "launchd" || echo "supervisord / other")

## Skills & Strengths

- {List key capabilities}

## Values

- {What this agent cares about}
SOUL
  ok "SOUL.md scaffolded at ${SOUL_FILE}"
  info "Edit ${SOUL_FILE} to describe who this agent is, then commit it."
fi

# ── Install services ───────────────────────────────────────────────────────────
if [[ -f "${WORKSPACE}/deploy/install-queue-worker.sh" ]]; then
  info "Installing queue worker..."
  bash "${WORKSPACE}/deploy/install-queue-worker.sh" 2>/dev/null && ok "Queue worker installed"
fi

if [[ -f "${WORKSPACE}/deploy/install-bus-listener.sh" ]]; then
  info "Installing bus listener..."
  bash "${WORKSPACE}/deploy/install-bus-listener.sh" 2>/dev/null && ok "Bus listener installed"
fi

echo
bold "══ Next Steps ═══════════════════════════════════════════"
info "1. Edit your SOUL.md and commit it to the fleet repo"
info "2. Verify AccFS:  mountpoint -q ~/.acc/shared && echo mounted"
info "3. Check status:  bash deploy/agent-pull.sh"
info "4. View in dashboard: ${ACC_URL}/agents/${AGENT_NAME}"
echo
bold "Agent setup complete."
