#!/usr/bin/env bash
# hub-setup.sh — Interactive setup wizard for CCC hub node.
# Run once on the machine that will host acc-server and AccFS.
# Generates ~/.acc/.env, /srv/accfs, and registers SMB secrets.

set -euo pipefail

ACC_DIR="${HOME}/.acc"
ENV_FILE="${ACC_DIR}/.env"

# ── Helpers ────────────────────────────────────────────────────────────────────
bold()  { printf '\033[1m%s\033[0m\n' "$*"; }
ask()   { local prompt="$1" default="${2:-}" var; read -rp "$(bold "$prompt") [${default}]: " var; echo "${var:-$default}"; }
askq()  { local prompt="$1" var; read -rsp "$(bold "$prompt"): " var; echo; echo "$var"; }
info()  { printf '  → %s\n' "$*"; }
ok()    { printf '  ✓ %s\n' "$*"; }
warn()  { printf '  ⚠ %s\n' "$*" >&2; }

echo
bold "═══════════════════════════════════════════════════════"
bold " CCC Hub Setup Wizard"
bold "═══════════════════════════════════════════════════════"
echo
echo "This wizard configures the hub node that runs acc-server,"
echo "the AccFS (Samba) share, and all central services."
echo

# ── Collect values ─────────────────────────────────────────────────────────────
AGENT_NAME=$(ask "Hub agent name" "$(hostname -s)")
AGENT_HOST=$(ask "Hostname (as seen by other agents)" "$(hostname -s)")

CCC_PORT=$(ask "CCC API port" "8789")
TOKENHUB_PORT=$(ask "Tokenhub port" "8090")

# Auto-detect Tailscale IP
TAILSCALE_IP=""
TAILSCALE_IP=$(tailscale ip -4 2>/dev/null | head -1 || true)
TAILSCALE_IP=$(ask "Tailscale IP (for agent-to-hub communication)" "${TAILSCALE_IP}")

PUBLIC_HOST=$(ask "Public IP or domain (for external access, e.g. CI/CD)" "${TAILSCALE_IP}")

SMB_SHARE=$(ask "AccFS SMB share name" "accfs")
SMB_USER=$(ask "SMB/system username" "$(whoami)")
SMB_PASS=$(askq "AccFS SMB password (will be stored in tokenhub, not written to disk)")

ANTHROPIC_KEY=$(askq "Anthropic API key (optional, press Enter to skip)")
NVIDIA_KEY=$(askq "NVIDIA inference API key (optional, press Enter to skip)")

SLACK_BOT=$(askq "Slack bot token (optional, press Enter to skip)")
TELEGRAM_TOKEN=$(askq "Telegram bot token (optional, press Enter to skip)")

CCC_DOMAIN=$(ask "Public domain for published content (optional)" "")

echo
bold "══ Summary ══════════════════════════════════════════════"
info "Agent name:   ${AGENT_NAME}"
info "Hub IP:       ${TAILSCALE_IP}"
info "Public host:  ${PUBLIC_HOST}"
info "CCC port:     ${CCC_PORT}"
info "SMB share:    ${SMB_SHARE} (user: ${SMB_USER})"
echo

# ── Create ~/.acc structure ────────────────────────────────────────────────────
mkdir -p "${ACC_DIR}/logs" "${ACC_DIR}/data" "${ACC_DIR}/bin"

# ── Write .env ─────────────────────────────────────────────────────────────────
cat > "${ENV_FILE}" << EOF
# CCC Hub Configuration — generated by deploy/wizard/hub-setup.sh
# Do not commit this file.

# Identity
AGENT_NAME=${AGENT_NAME}
AGENT_HOST=${AGENT_HOST}

# Network
ACC_URL=http://localhost:${CCC_PORT}
PUBLIC_HOST=${PUBLIC_HOST}
CCC_PORT=${CCC_PORT}
TOKENHUB_PORT=${TOKENHUB_PORT}
TOKENHUB_URL=http://localhost:${TOKENHUB_PORT}
ANTHROPIC_BASE_URL=http://localhost:9099

# Storage
ACC_FS_ROOT=/srv/accfs
SMB_HOST=${TAILSCALE_IP}
SMB_SHARE=${SMB_SHARE}
SMB_USER=${SMB_USER}

# Inference
$([ -n "$ANTHROPIC_KEY" ] && echo "ANTHROPIC_API_KEY=${ANTHROPIC_KEY}" || echo "# ANTHROPIC_API_KEY=")
$([ -n "$NVIDIA_KEY" ] && echo "NVIDIA_API_KEY=${NVIDIA_KEY}" || echo "# NVIDIA_API_KEY=")

# Channels
$([ -n "$SLACK_BOT" ] && echo "SLACK_BOT_TOKEN=${SLACK_BOT}" || echo "# SLACK_BOT_TOKEN=")
$([ -n "$TELEGRAM_TOKEN" ] && echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_TOKEN}" || echo "# TELEGRAM_BOT_TOKEN=")
$([ -n "$CCC_DOMAIN" ] && echo "CCC_DOMAIN=${CCC_DOMAIN}" || echo "# CCC_DOMAIN=")
EOF
chmod 600 "${ENV_FILE}"
ok ".env written to ${ENV_FILE}"

# ── Set up /srv/accfs ──────────────────────────────────────────────────────────
if [[ ! -d /srv/accfs ]]; then
  sudo mkdir -p /srv/accfs
  sudo chown "$(id -u):$(id -g)" /srv/accfs
  ok "Created /srv/accfs"
else
  ok "/srv/accfs already exists"
fi

# ── Write Samba config ─────────────────────────────────────────────────────────
if command -v samba &>/dev/null || command -v smbd &>/dev/null; then
  SMBD_CONF=$(cat << SMBCONF
[${SMB_SHARE}]
   path = /srv/accfs
   read only = no
   browsable = yes
   valid users = ${SMB_USER}
   create mask = 0664
   directory mask = 0775
SMBCONF
)
  if ! grep -q "\[${SMB_SHARE}\]" /etc/samba/smb.conf 2>/dev/null; then
    echo "$SMBD_CONF" | sudo tee -a /etc/samba/smb.conf > /dev/null
    ok "Added [${SMB_SHARE}] share to /etc/samba/smb.conf"
  fi
  printf '%s\n%s\n' "${SMB_PASS}" "${SMB_PASS}" | sudo smbpasswd -s -a "${SMB_USER}" 2>/dev/null && ok "Samba password set for ${SMB_USER}"
  sudo systemctl restart smbd 2>/dev/null && ok "smbd restarted"
else
  warn "Samba not installed — install samba and run: sudo smbpasswd -a ${SMB_USER}"
fi

# ── Store secrets in tokenhub (once it's running) ─────────────────────────────
# Secrets will be stored via /api/secrets after acc-server starts
cat >> "${ENV_FILE}" << EOF

# Populated by wizard — store in tokenhub after first start:
# SMB_PASSWORD=${SMB_PASS}
# (run: deploy/migrations/0019_migrate_minio_to_accfs.sh to push to secrets API)
EOF

echo
bold "══ Next Steps ═══════════════════════════════════════════"
info "1. Install and start acc-server:   sudo systemctl enable --now acc-server"
info "2. Install tokenhub:               cd ~/Src/tokenhub && ./install.sh"
info "3. Register this hub agent:        bash deploy/register-agent.sh"
info "4. Push SMB password to secrets:   bash deploy/migrations/0019_migrate_minio_to_accfs.sh"
info "5. Install queue worker:           bash deploy/install-queue-worker.sh"
info "6. Install bus listener:           bash deploy/install-bus-listener.sh"
info "7. Add other agents:               bash deploy/wizard/agent-setup.sh  (on each agent)"
echo
bold "Hub setup complete."
